js/accordion.js
Asana Task - https://app.asana.com/0/164174452236961/653474809011396/f
=> Filter for sui-accordion-item-content class

js/select2.full.js
=> Revert "Fix/select2 webpack incompatible"

index.html
Update showcase and its code snippet of `toggle with label`, to allow change checked attribute on label click
=> Fix showcase of toggles with label

scss/_layout.scss, showcase-assets/showcase.scss
Asana task: https://app.asana.com/0/164174452236961/668720538224319
=> [Fix] Form layout when using grid has incorrect spacing

index.html, scss/_forms.scss
Asana task: https://app.asana.com/0/164174452236961/666569797617458
=> [New] Input field with icon

scss/_colors.scss, scss/_tooltips.scss
Asana task: https://app.asana.com/0/164174452236961/665691505027411
=> [Improvement] Tooltip styles

scss/_pagination.scss
https://app.asana.com/0/385581670491499/837182528287412
=> [update] pagination filter footer

scss/_boxes.scss
https://app.asana.com/0/385581670491499/837182528287408
=> [improvement] box search padding

scss/_boxes.scss
https://app.asana.com/0/57692755263536/841074921510552
=> [Improvement] Box settings side column width it's bigger than design.

scss/_accordions.scss
https://app.asana.com/0/57692755263536/842263367716722
=> [Improvement] Footer for flexbox accordions

index.html, scss/_radio-checkbox.scss
https://app.asana.com/0/57692755263536/841074921510556
=> [Improvement] Radio and checkbox options with image.

scss/_colorpickers.scss, scss/_colors.scss, scss/_variables.scss, scss/shared-ui.scss
https://app.asana.com/0/57692755263536/843679439803813
=> [New] Color pickers

index.html, js/sidenav-input.js, scss/_sidenav.scss
https://app.asana.com/0/385581670491499/850533785994268
=> [Improvement] Side navigation with floating input.

scss/_tabs.scss
https://app.asana.com/0/385581670491499/850533785994273
=> [Fix] Flushed tabs inside box body.

scss/_header.scss
https://app.asana.com/0/385581670491499/850533785994264
=> [Improvement] Header with floating input.

scss/_tabs.scss
https://app.asana.com/0/385581670491499/851514319508211
=> [Improvement] New variation for side-tabs.

index.html, scss/_colors.scss, scss/_footer.scss, scss/_sidenav.scss
https://app.asana.com/0/164174452236961/851706694775846
=> [Improvement] Footer navigation and social links.

scss/_ace-editor.scss
https://app.asana.com/0/57692755263536/853955490508720
=> [Fix] ACE selector overflows container.

scss/_select.scss
https://app.asana.com/0/57692755263536/853972113056128
=> [Fix] Select height is wrong.

scss/_boxes.scss
https://app.asana.com/0/385581670491499/858016091185114
=> [Bug] Sticky box not working with sidenav.

index.html, scss/_notifications.scss
https://app.asana.com/0/164174452236961/864179462665772
=> [Improvement] We need a "loading" notification.

scss/_box-selectors.scss
https://app.asana.com/0/385581670491499/866578268602606
=> [Improvement] Box selectors with reduced spacing.

scss/_modals.scss
https://app.asana.com/0/385581670491499/866150382696104
=> [Improvement] Styles for alternative dialog header image.

index.html, scss/_box-settings.scss
https://app.asana.com/0/164174452236961/866711359712739
=> [Improvement] Box settings variation without border and padding.

index.html
https://app.asana.com/0/164174452236961/877790165255373
=> [Bug] Missing typo on sample code for dropdown element.

scss/_summary.scss
https://app.asana.com/0/164174452236961/877680461485364
=> [Bug] Vertical spacing reduced on summary boxes after white-label changes.

index.html, js/accordion.js, scss/_accordions.scss
https://app.asana.com/0/164174452236961/877790165255372
=> [Fix] Child accordions don't open.

index.html, scss/_colors.scss, scss/_progress-bars.scss, scss/_variables.scss
https://app.asana.com/0/164174452236961/877449317419929
=> [Enhance] Progress bars new design.

index.html, scss/_select2.scss
https://app.asana.com/0/164174452236961/879927174706002
=> [Enhance] Select samples and documentation

js/password.js
https://app.asana.com/0/164174452236961/880897803049358
=> [Fix] Check if form field has password input.

index.html, scss/_box-builder.scss, scss/_buttons.scss, scss/_colors.scss, scss/_variables.scss, scss/shared-ui.scss
https://app.asana.com/0/164174452236961/879984410625946
=> [New] Box builder element

index.html, scss/_sidenav.scss
https://app.asana.com/0/164174452236961/883600650459145
https://app.asana.com/0/164174452236961/892931136204444
=> [Enhance] Side navigation styles and sticky class.

index.html, scss/_accordions.scss
https://app.asana.com/0/164174452236961/902026416791515
=> [Improvement] Accordion blocks responsive design.

CHANGELOG.md, scss/_sidenav.scss
https://app.asana.com/0/164174452236961/905633085619817
=> [Fix] Side navigation input overlapping notices

CHANGELOG.md, scss/sui-wp-editor.scss
https://app.asana.com/0/164174452236961/926987973896855
=> [Enhance] Wysiwyg editor content links need to be the same blue from SUI.

CHANGELOG.md, scss/_color-accessibility.scss
Asana Task - https://app.asana.com/0/164174452236961/933059382480615/f
=> Improve ace editor accessibility

scss/_color-accessibility.scss
https://app.asana.com/0/47431170559378/943870334768685
=> Accessibility Theme - Text align buttons

CHANGELOG.md, index.html, scss/_box-builder.scss
https://app.asana.com/0/1110928411916236/1111286941632572
=> [Improvement] Box builder empty message with image.

CHANGELOG.md, scss/_box-builder.scss
https://app.asana.com/0/1110928411916236/1111286941632568
=> [Improvement] Box builder footer with hidden elements.

CHANGELOG.md, index.html, scss/_box-builder.scss
https://app.asana.com/0/1110928411916236/1111286941632561
=> [Improvement] Builder box header with multi-line options.

CHANGELOG.md, index.html, js/dialog-slider.js, scss/_animations.scss, scss/_modals.scss, scss/_variables.scss
https://app.asana.com/0/1111636116819815/1113260833946725
=> On boarding slider dialog

scss/_modals.scss
https://app.asana.com/0/1117257152802141/1117256874738899
=> [enhance] apply last-child styles to element using sui-last class.

CHANGELOG.md, scss/_colorpickers.scss
https://app.asana.com/0/1117257152802141/1117256874738903
=> [fix] color pickers are broken on ie11

CHANGELOG.md, index.html, js/side-tabs.js, showcase-assets/showcase.js
https://app.asana.com/0/1117257152802141/1119769348185988
=> Side tabs function

CHANGELOG.md, index.html, scss/_tree-fancy.scss, scss/shared-ui.scss
https://app.asana.com/0/1119769348185994/1120936421626565
=> [New] Fancy tree with SUI styles.

CHANGELOG.md, scss/_boxes.scss, scss/_sidenav.scss
Asana task link:
https://app.asana.com/0/1122947274410463/1123318781585782
=> [Improvement] When using boxes inside of grid, it has double bottom margin.

.gitignore, CHANGELOG.md, scss/_box-settings.scss
Asana task link:
https://app.asana.com/0/1122947274410463/1123281131655801
=> [Fix] [Box Settings] On small screens flushed box settings doesn't properly align to left.

CHANGELOG.md, scss/_accordions.scss
https://app.asana.com/0/1124920089528476/1125107450700687
=> [Fix] [Accordions] Missing spacing at bottom of content.

CHANGELOG.md, index.html, js/select2.js, scss/_color-accessibility.scss, scss/_search.scss, scss/_tags.scss, scss/shared-ui.scss
https://app.asana.com/0/1135738179704206/1125272876399379
=> [new] search select element.

CHANGELOG.md, index.html, js/select2.js, scss/_color-accessibility.scss, scss/_search.scss, scss/_tags.scss, scss/shared-ui.scss
https://app.asana.com/0/1135738179704206/1125272876399379
=> [Improvement] Add new 'Small' 18px sized tags.

CHANGELOG.md, index.html, js/select2.js, js/tabs.js, scss/_color-accessibility.scss, scss/_search.scss, scss/_tags.scss, scss/shared-ui.scss
https://app.asana.com/0/1135738179704206/1136965038533441
=> [Enhance] Allow callback functions for tabs.

CHANGELOG.md, js/sticky-box.js
Task: https://app.asana.com/0/1136989724262249/1126979977714653
=> [Bug] Sticky box has shadow when not sticky after changing tab

CHANGELOG.md, index.html, js/sticky-box.js, scss/_buttons.scss
Task: https://app.asana.com/0/1136989724262249/1128787643445371
=> [New] Add a new variation of loading buttons with helper text

CHANGELOG.md, assets/scss/shared-ui/_modals.scss
https://app.asana.com/0/1149284078386817/1151077366153203
=> [fix] [element: modals] broken overlay for medium and small screens.

CHANGELOG.md, assets/js/shared-ui/select.js, assets/js/shared-ui/select2.js, assets/scss/shared-ui/_forms.scss, assets/scss/shared-ui/_select2.scss
https://app.asana.com/0/1143291364557401/1148850975318451
=> [Fix] Insert Variables: Select2 not rendering dropdown options.

assets/js/shared-ui/multistrings.js
-Clean up existing values on load
-Add values in a new line in the hidden textbox when a new value is added in the visibile input
-Prevent spaces and commas from being added in new values
-Adjust visible tags when editing the hidden textbox
=> Adjust handling of multiple strings input

assets/scss/shared-ui/_tooltips.scss
https://app.asana.com/0/1146647951415570/1148850975318459
=> [Bug] [Element: Tooltip] Styling is too padded.

CHANGELOG.md, assets/scss/shared-ui/_box-selectors.scss, page-selectors.html
https://app.asana.com/0/1146647951415570/1154457560114289
=> [Improvement] [Element: Selectors] Disabled pro options.

CHANGELOG.md, assets/scss/shared-ui/_icons.scss, page-icons.html
https://app.asana.com/0/1165305016352913/1158470402825377
=> [Bug] [Icons Font] Branda icon is missing even when font supports it.

assets/scss/shared-ui/_colors.scss, page-buttons.html, page-icon-buttons.html
https://app.asana.com/0/1165305016352913/1167143869569809
=> [update] [buttons] add white color variation.

assets/js/shared-ui/select2.js
Fixes the error reported by Hassan [here](https://incsub.slack.com/archives/C9C090FFW/p1614339608015600) when the selects are initialized automatically by SUI
=> Make the .sui-version div the default dropdownParent for select2

_config.yml
=> 📝 docs(upsells): Move "Upsells Box" section to the new "Upsells" category.

assets/scss/shared-ui/_box-settings.scss, assets/scss/shared-ui/_color-accessibility.scss, assets/scss/shared-ui/_forms.scss, assets/scss/shared-ui/_toggles.scss, assets/scss/shared-ui/_typography.scss, page-select.html, page-trees.html, page-utilities.html
Margin for the next paragraph in the description is added.
=> 🐛 fix(typography): Descriptions need to be multi-line.

assets/scss/shared-ui/_colors.scss, assets/scss/shared-ui/_radio-checkbox.scss
added hover and focus effects for checkbox and radiobox.
This css applies for both checkbox and radiobox as same css is getting used for both elements.
=> new(checkbox): Focus state styles.

assets/js/shared-ui/modal-dialog.js, page-modals.html
add "data-modal-animated" action and sample modal and changes in documentation.
=> new(modals): Add option for disabling open/close modal effects.

assets/scss/shared-ui/_calendar-range.scss
https://app.asana.com/0/164174452236961/1174593981258777/f
=> fix(date-picker): Ranges overlapping the calendar after a certain amount.

assets/scss/shared-ui/_calendar-range.scss
https://app.asana.com/0/164174452236961/1174593981258779/f
It might be good to check this other PR first. This will look better afterwards
https://github.com/wpmudev/shared-ui/pull/297
=> fix(calendar): Looking off in mobile.

assets/js/shared-ui/multistrings.js
=> fix(multistrings): Undefined is not a possible return value of `typeof`.

assets/js/shared-ui/tabs.js
=> fix(tabs): On `keyDownEventListener` the body of case clause duplicates.

assets/js/shared-ui/ace/ace.js
fixed ace error while using with wp bakery builder
=> fix(code-editor): ACE conflict with WPBakery Page Builder.

CHANGELOG.md
=> 🔊 Update changelog file.

assets/js/shared-ui/select2.js
=> 🐛 fix(insert-variables): insert variables outputs null when selecting.

CHANGELOG.md
- **fix(insert-variables):** Insert variables outputs null when selecting. [#545](https://github.com/wpmudev/shared-ui/pull/545) ([SUI-573](https://incsub.atlassian.net/browse/SUI-573)) ([@creador-dev](https://github.com/creador-dev))
- **fix(multi select):** Select2 multi select disappearing issue. [#562](https://github.com/wpmudev/shared-ui/pull/541) ([SUI-562](https://incsub.atlassian.net/browse/SUI-570)) ([@creador-dev](https://github.com/creador-dev))
- **fix(accordion):** Accordion item focus issue. [#544](https://github.com/wpmudev/shared-ui/pull/544) ([SUI-571](https://incsub.atlassian.net/browse/SUI-571)) ([@creador-dev](https://github.com/creador-dev))
=> 🔊 Update CHANGELOG.md
